// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

import 'dotenv/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Ovaj config čita samo Prisma CLI (migracije, studio), ne i aplikacija,
    // koja ide preko lib/prisma.ts i DATABASE_URL varijable.
    // Zato ovde ima prednost direktna konekcija, jer PgBouncer ne podržava
    // DDL operacije pouzdano.
    url: process.env['DATABASE_URL_UNPOOLED'] ?? process.env['DATABASE_URL'],
  },
});
